# See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

# pod lifecycle!
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo-app
spec:
  # best used WITHOUT HPA
  # replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: newtalks-k8s-backend
        image: ghcr.io/ioxua/newtalk-k8s-demo:latest
        env:
          - name: API_URL
            valueFrom:
              configMapKeyRef:
                name: demo-configmap
                key: app_uri
          - name: MY_SECRET
            valueFrom:
              secretKeyRef:
                name: demo-secrets
                key: my-secret-key
        ports:
        - containerPort: 8080
          name: http-port

        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        # https://sysdig.com/blog/kubernetes-limits-requests/
        resources:
          requests:
            memory: 100Mi
            cpu: 250m
          limits:
            memory: 600Mi
            cpu: 750m
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: http-port
    # targetPort: 8080

---
# see https://kubernetes.io/docs/concepts/configuration/configmap/#configmaps-and-pods
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  app_uri: "https://pokeapi.co/api/v2/"
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: demo-secrets
# data:
#   my-secret-key: a very secret string
# ---
# see https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#example
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: hello
# spec:
#   schedule: "* * * * *" # every minute
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: hello
#             image: busybox:1.28
#             imagePullPolicy: IfNotPresent
#             command:
#             - /bin/sh
#             - -c
#             - date; echo Hello from the Kubernetes cluster
#           restartPolicy: OnFailure
