# See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 8080

        # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        # https://sysdig.com/blog/kubernetes-limits-requests/
        resources:
          requests:
            memory: 100Mi
            cpu: 250m
          limits:
            memory: 200Mi
            cpu: 500m

