apiVersion: v1
kind: Pod
metadata:
  name: demo-simple-pod
spec:
  containers:
  - name: backend
    image: i-k8s-demo-img:latest
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: 100Mi
        cpu: 250m
      limits:
        memory: 200Mi
        cpu: 500m